version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" "$CIRCLE_TAG" "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_PROJECT_REPONAME" "$CIRCLE_BUILD_URL" \
            | tee version.json
      - store_artifacts:
          path: version.json
      - run: |
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
          docker build -t $DOCKER_USER/${DOCKER_IMAGE:-$CIRCLE_PROJECT_REPONAME} .
          docker push $DOCKER_USER/${DOCKER_IMAGE:-$CIRCLE_PROJECT_REPONAME}
